# Generated by Django 4.1.5 on 2023-06-09 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0006_rename_massage_comment_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacebookModel',
        ),
    ]
