# Generated by Django 4.1.5 on 2023-06-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0007_delete_facebookmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='tel',
            field=models.IntegerField(default='(234) ', max_length=11, null=True),
        ),
    ]
