# Generated by Django 4.1.5 on 2023-06-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0010_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
