# Generated by Django 4.1.5 on 2023-06-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0011_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(null=True, upload_to='bookApp/image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(null=True, upload_to='bookApp/image'),
        ),
    ]
