# Generated by Django 4.1.5 on 2023-06-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0012_alter_author_image_alter_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='bookApp/image'),
        ),
    ]
