# Generated by Django 4.1.5 on 2023-06-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0017_alter_author_image_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='telgram_url',
            new_name='instagram_url',
        ),
        migrations.AlterField(
            model_name='author',
            name='website_name',
            field=models.TextField(blank=True, default='ReadexIQ', null=True),
        ),
    ]
